@baseUrl = https://8080-marcoweb-j2projetomodel-z01bu7bpo93.ws-us110.gitpod.io

###
GET {{baseUrl}}/categorias

###
POST {{baseUrl}}/categorias
Content-Type: application/json

{
    "nome": "Conhecimentos Gerais"
}